services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vionet-sqlserver

    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}

    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: ../backend
      dockerfile: TripExpense.Api/Dockerfile

    container_name: trip-expense-api

    depends_on:
      - sqlserver

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS}
      RUN_SEED: ${RUN_SEED}

    ports:
      - "5149:8080"

volumes:
  sqlserver_data:
